# MRVN-vmt (c) by Bikkie / snake-biscuits [b!scuit#3659]
#
# MRVN-vmt is licensed under a
# Creative Commons Attribution-ShareAlike 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by-sa/4.0/>.
"""generate .vmt files from a folder of .vtf files"""
from __future__ import annotations
import fnmatch
import os
import re

from PIL import Image
from VTFLibWrapper import VTFLib  # need appropriate compiled VTFLib
# see VTFLibWrapper/README.md for links to Linux version


__version__ = "1.0.0"
# NOTE: cannot be bothered to convert .vmt proxies
# TODO: Titanfall 2 rpak .json materials -> .shader


patterns = {"alphatest": re.compile(r'\s"\$alphatest"\s1'),
            "basetexture": re.compile(r'\s"\$basetexture"\s"(.*)"'),
            "tooltexture": re.compile(r'\s%tooltexture\s"(.*)"')}


class VMT:
    basetexture: str = ""
    is_trans: bool = False
    tooltexture: str = None

    @classmethod
    def from_file(cls, filename: str) -> VMT:
        out = cls()
        with open(filename) as vmt_file:
            for line in vmt_file:
                if re.match(patterns["alphatest"], line) is not None:
                    out.is_trans = True
                match = re.match(patterns["basetexture"], line)
                if match is not None:
                    out.basetexture = match.groups()[0]
                match = re.match(patterns["tooltexture"], line)
                if match is not None:
                    out.tooltexture = match.groups()[0]
        return out


def vtf_to_tga(vtf_filename: str, tga_filename: str):
    vtf = VTFLib.VTFLib()
    vtf.image_load_from_buffer(open(vtf_filename, "rb").read())
    vtf_rgba32 = bytes(vtf.convert_to_rgba8888().contents)
    tga = Image.frombytes("RGBA", (vtf.width(), vtf.height()), vtf_rgba32, "raw")
    os.makedirs(os.path.dirname(tga_filename), exist_ok=True)
    tga.save(tga_filename)


def filename(folder: str, base: str, ext: str) -> str:
    return os.path.join(folder, f"{base}.{ext}")


# TODO: textures -> shader_names for TrenchBroom
def convert_folder(materials_dir: str, MRVN_dir: str, MRVN_game: str,
                   recursive=False, subfolder: str = "", verbose=False):
    # e.g. "../titanfall1_extracted_textures", "C:/MRVN-radiant", "titanfallonline"
    materials_dir = os.path.realpath(materials_dir)
    MRVN_dir = os.path.realpath(MRVN_dir)
    scripts_dir = os.path.join(MRVN_dir, MRVN_game, "scripts")
    textures_dir = os.path.join(MRVN_dir, MRVN_game, "textures")
    # NOTE: just directly grab all the world textures
    top_folder = os.path.join(materials_dir, "world", subfolder)
    for folder in os.listdir(os.path.join(materials_dir, "world", subfolder)):
        vmt_folder = os.path.join(top_folder, folder)
        if not os.path.isdir(vmt_folder):
            continue
        shader_prefix = subfolder.replace("\\", "/").replace("/", "_") + "_" if subfolder != "" else ""
        if verbose:
            print(f"*** {shader_prefix}{folder}.shader")
        shader_file = open(os.path.join(scripts_dir, f"{shader_prefix}{folder}.shader"), "w")
        shader_file.write("// Generated by MRVN-vmt\n")
        count = 0
        for vmt_filename in fnmatch.filter(os.listdir(vmt_folder), "*.vmt"):
            # .vmt
            vmt = VMT.from_file(os.path.join(vmt_folder, vmt_filename))
            if vmt.basetexture == "" and vmt.tooltexture is None:
                if verbose:
                    print(f"!!! {vmt_filename} has no texture !!!")
                continue
            shader_name = os.path.join("textures", "world", subfolder, folder, vmt_filename[:-4])
            shader_file.write(f"\n{shader_name}\n" + "{\n")
            # shader_file.write(f"\tqer_editorimage {shader_name}.tga\n")
            texture = vmt.basetexture if vmt.tooltexture is None else vmt.tooltexture
            shader_file.write(f"\tqer_editorimage {os.path.join('textures', texture)}.tga\n")
            # TODO: convert as much of the shader as possible
            if vmt.is_trans:
                # NOTE: should really target basetexture, but we rename it later
                shader_file.write("\t{\n\t\tmap " + os.path.join("textures", shader_name) + ".tga\n")
                # shader_file.write("\t{\n\t\tmap " + os.path.join("textures", vmt.basetexture) + ".tga\n")
                shader_file.write("\t\tblendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA\n\t}\n")
            shader_file.write("}\n")
            # .vtf
            vtf_filename = filename(materials_dir, texture, "vtf")
            if not os.path.exists(vtf_filename):
                if verbose:
                    print(f"!!! {vmt_filename} texture {texture} not found !!!")
                continue
            # vtf_to_tga(vtf_filename, filename(os.path.join(MRVN_dir, MRVN_game), shader_name, "tga"))
            # ^ rename vtf to shader_name, good for trenchbroom
            if vmt.basetexture != "":
                vtf_to_tga(vtf_filename, filename(textures_dir, vmt.basetexture, "tga"))
            if vmt.tooltexture is not None:
                vtf_to_tga(vtf_filename, filename(textures_dir, vmt.tooltexture, "tga"))
            count += 1
        shader_file.close()
        if verbose:
            print(f"--- {count} materials converted")
        if count == 0:
            os.remove(os.path.realpath(shader_file.name))
        if recursive:
            convert_folder(materials_dir, MRVN_dir, MRVN_game, True, os.path.join(subfolder, folder), verbose=verbose)


if __name__ == "__main__":
    import sys

    # materials_dir = "E:/Mod/TitanfallOnline/TitanFallOnline/assets_dump/materials"
    # MRVN_dir = "E:/Mod/_tools/Source Engine - Respawn/MRVN-radiant-3db242a-Windows-x86_64"
    if len(sys.argv) == 3:
        materials_dir, MRVN_dir = sys.argv[1:]
    # elif len(sys.argv) == 1:
    #     pass  # use defaults
    else:
        print(f'Usage: {sys.argv[0]} "Titanfall materials dir" "MRVN-radiant install dir"')
        print('\tif you can\'t find your "Titanfall/materials" folder, extract it from the .vpks')
        sys.exit()

    sys.stdout.reconfigure(line_buffering=True)  # for piping print to logfile
    convert_folder(materials_dir, MRVN_dir, "titanfallonline", True, verbose=True)
    # TODO: concatenate .shader files together into a top-level .shader for each world/ folder
